In [1]:
# Install driver
!pip3 install psycopg2-binary

Defaulting to user installation because normal site-packages is not writeable
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Downloading psycopg2_binary-2.9.12-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 97.0 MB/s  0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12

In [4]:
!pip3 install sqlalchemy psycopg2-binary
print(

Defaulting to user installation because normal site-packages is not writeable
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.50-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.5 kB)
Requirement already satisfied: psycopg2-binary in /home/rocky/.local/lib/python3.9/site-packages (2.9.12)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.2.5-cp39-cp39-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (4.1 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in /home/rocky/.local/lib/python3.9/site-packages (from sqlalchemy) (4.15.0)
Downloading sqlalchemy-2.0.50-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 89.6 MB/s  0:00:00
Downloading greenlet-3.2.5-cp39-cp39-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (587 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 587.5/587.5 kB 32.8 MB/s  0:00:00
Installing collected packages: greenlet, sqlalchemy
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [sqlalchemy] 1/2 [sqlalchemy]
Successfully installed greenlet-3.2.5 sqlalchemy-2.0.50

In [1]:
# Connect to PostgreSQL
from sqlalchemy import create_engine
import pandas as pd

In [2]:
engine = create_engine('postgresql://postgres:password@localhost:5432/postgres')

In [4]:
df = pd.read_sql('SELECT * FROM complaints', engine)
print(df.shape)
df.head()

(1282355, 18)

,date_received,product,sub_product,issue,sub_issue,consumer_narrative,company_public_response,company,state,zip_code,tags,consumer_consent,submitted_via,date_sent,company_response,timely_response,consumer_disputed,complaint_id
0,05/10/2019,Checking or savings account,Checking account,Managing an account,Problem using a debit or ATM card,None,None,NAVY FEDERAL CREDIT UNION,FL,328XX,Older American,None,Web,05/10/2019,In progress,Yes,N/A,3238275
1,05/10/2019,Checking or savings account,Other banking product or service,Managing an account,Deposits and withdrawals,None,None,BOEING EMPLOYEES CREDIT UNION,WA,98204,None,N/A,Referral,05/10/2019,Closed with explanation,Yes,N/A,3238228
2,05/10/2019,Debt collection,Payday loan debt,Communication tactics,Frequent or repeated calls,None,None,CURO Intermediate Holdings,TX,751XX,None,None,Web,05/10/2019,Closed with explanation,Yes,N/A,3237964
3,05/10/2019,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Old information reappears or never goes away,None,None,Ad Astra Recovery Services Inc,LA,708XX,None,None,Web,05/10/2019,Closed with explanation,Yes,N/A,3238479
4,05/10/2019,Checking or savings account,Checking account,Managing an account,Banking errors,None,None,ALLY FINANCIAL INC.,AZ,85205,None,N/A,Postal mail,05/10/2019,In progress,Yes,N/A,3238460

In [5]:
query = """
    SELECT * FROM complaints
    WHERE company IN (
        'EQUIFAX, INC.', 
        'Experian Information Solutions Inc.',
        'TRANSUNION INTERMEDIATE HOLDINGS, INC.'
    )
"""

df_bureaus = pd.read_sql(query, engine)
print(df_bureaus.shape)
df_bureaus.head()

(316074, 18)

,date_received,product,sub_product,issue,sub_issue,consumer_narrative,company_public_response,company,state,zip_code,tags,consumer_consent,submitted_via,date_sent,company_response,timely_response,consumer_disputed,complaint_id
0,05/09/2019,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Information belongs to someone else,None,None,"EQUIFAX, INC.",NC,276XX,None,None,Web,05/09/2019,Closed with explanation,Yes,N/A,3236855
1,05/09/2019,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Information belongs to someone else,None,None,"EQUIFAX, INC.",CA,949XX,Older American,None,Web,05/09/2019,Closed with explanation,Yes,N/A,3236867
2,05/09/2019,Debt collection,Other debt,Attempts to collect debt not owed,Debt was result of identity theft,None,None,"EQUIFAX, INC.",TX,77082,None,None,Web,05/09/2019,Closed with explanation,Yes,N/A,3236934
3,05/09/2019,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Public record information inaccurate,None,None,"EQUIFAX, INC.",GA,30126,None,N/A,Fax,05/09/2019,Closed with explanation,Yes,N/A,3236941
4,05/09/2019,"Credit reporting, credit repair services, or o...",Credit reporting,Problem with a credit reporting company's inve...,Difficulty submitting a dispute or getting inf...,None,None,"EQUIFAX, INC.",NC,28540,None,None,Web,05/09/2019,Closed with explanation,Yes,N/A,3236914